In [387]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# Import OS and JSON Modules
import os, json

In [388]:
filename = ('Data/superhero_info.csv')
df = pd.read_csv(filename)
df.head()

,Hero|Publisher,Gender,Race,Alignment,Hair color,Eye color,Skin color,Measurements
0,A-Bomb|Marvel Comics,Male,Human,good,No Hair,yellow,Unknown,"{'Height': '203.0 cm', 'Weight': '441.0 kg'}"
1,Abe Sapien|Dark Horse Comics,Male,Icthyo Sapien,good,No Hair,blue,blue,"{'Height': '191.0 cm', 'Weight': '65.0 kg'}"
2,Abin Sur|DC Comics,Male,Ungaran,good,No Hair,blue,red,"{'Height': '185.0 cm', 'Weight': '90.0 kg'}"
3,Abomination|Marvel Comics,Male,Human / Radiation,bad,No Hair,green,Unknown,"{'Height': '203.0 cm', 'Weight': '441.0 kg'}"
4,Absorbing Man|Marvel Comics,Male,Human,bad,No Hair,blue,Unknown,"{'Height': '193.0 cm', 'Weight': '122.0 kg'}"

In [389]:
filename2 = ('Data/superhero_powers.csv')
df2 = pd.read_csv(filename2)
df2.head()

    hero_names                                             Powers
0      3-D Man         Agility,Super Strength,Stamina,Super Speed
1       A-Bomb  Accelerated Healing,Durability,Longevity,Super...
2   Abe Sapien  Agility,Accelerated Healing,Cold Resistance,Du...
3     Abin Sur                                 Lantern Power Ring
4  Abomination  Accelerated Healing,Intelligence,Super Strengt...

## Info Dataframe

In [390]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 463 entries, 0 to 462
Data columns (total 8 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Hero|Publisher  463 non-null    object
 1   Gender          463 non-null    object
 2   Race            463 non-null    object
 3   Alignment       463 non-null    object
 4   Hair color      463 non-null    object
 5   Eye color       463 non-null    object
 6   Skin color      463 non-null    object
 7   Measurements    463 non-null    object
dtypes: object(8)
memory usage: 29.1+ KB

In [391]:
df['Hero|Publisher'].value_counts()

Spider-Man|Marvel Comics       3
Black Canary|DC Comics         2
Nova|Marvel Comics             2
Toxin|Marvel Comics            2
Batman|DC Comics               2
                              ..
Fabian Cortez|Marvel Comics    1
Exodus|Marvel Comics           1
Evilhawk|Marvel Comics         1
Evil Deadpool|Marvel Comics    1
Zoom|DC Comics                 1
Name: Hero|Publisher, Length: 457, dtype: int64

**Split Hero|Publisher**

In [392]:
df['Hero|Publisher'].str.split('|', expand=True)

                   0                  1
0             A-Bomb      Marvel Comics
1         Abe Sapien  Dark Horse Comics
2           Abin Sur          DC Comics
3        Abomination      Marvel Comics
4      Absorbing Man      Marvel Comics
..               ...                ...
458     Yellowjacket      Marvel Comics
459  Yellowjacket II      Marvel Comics
460             Yoda       George Lucas
461          Zatanna          DC Comics
462             Zoom          DC Comics

[463 rows x 2 columns]

In [393]:
# save two new columns into dataframe
df[['Hero','Publisher']] = df['Hero|Publisher'].str.split('|', expand=True)
df.head()

,Hero|Publisher,Gender,Race,Alignment,Hair color,Eye color,Skin color,Measurements,Hero,Publisher
0,A-Bomb|Marvel Comics,Male,Human,good,No Hair,yellow,Unknown,"{'Height': '203.0 cm', 'Weight': '441.0 kg'}",A-Bomb,Marvel Comics
1,Abe Sapien|Dark Horse Comics,Male,Icthyo Sapien,good,No Hair,blue,blue,"{'Height': '191.0 cm', 'Weight': '65.0 kg'}",Abe Sapien,Dark Horse Comics
2,Abin Sur|DC Comics,Male,Ungaran,good,No Hair,blue,red,"{'Height': '185.0 cm', 'Weight': '90.0 kg'}",Abin Sur,DC Comics
3,Abomination|Marvel Comics,Male,Human / Radiation,bad,No Hair,green,Unknown,"{'Height': '203.0 cm', 'Weight': '441.0 kg'}",Abomination,Marvel Comics
4,Absorbing Man|Marvel Comics,Male,Human,bad,No Hair,blue,Unknown,"{'Height': '193.0 cm', 'Weight': '122.0 kg'}",Absorbing Man,Marvel Comics

In [394]:
# drop original column
df = df.drop(columns = ['Hero|Publisher'])
df.head()

,Gender,Race,Alignment,Hair color,Eye color,Skin color,Measurements,Hero,Publisher
0,Male,Human,good,No Hair,yellow,Unknown,"{'Height': '203.0 cm', 'Weight': '441.0 kg'}",A-Bomb,Marvel Comics
1,Male,Icthyo Sapien,good,No Hair,blue,blue,"{'Height': '191.0 cm', 'Weight': '65.0 kg'}",Abe Sapien,Dark Horse Comics
2,Male,Ungaran,good,No Hair,blue,red,"{'Height': '185.0 cm', 'Weight': '90.0 kg'}",Abin Sur,DC Comics
3,Male,Human / Radiation,bad,No Hair,green,Unknown,"{'Height': '203.0 cm', 'Weight': '441.0 kg'}",Abomination,Marvel Comics
4,Male,Human,bad,No Hair,blue,Unknown,"{'Height': '193.0 cm', 'Weight': '122.0 kg'}",Absorbing Man,Marvel Comics

**Make Dictionary**

In [395]:
coord = df.loc[0,"Measurements"]
print(type(coord))
coord

<class 'str'>

"{'Height': '203.0 cm', 'Weight': '441.0 kg'}"

In [396]:
# Replace single quotes
coord = coord.replace("'",'"')
coord

'{"Height": "203.0 cm", "Weight": "441.0 kg"}'

In [397]:
# Use json.loads
fixed_coord = json.loads(coord)
print(type(fixed_coord))
fixed_coord

<class 'dict'>

{'Height': '203.0 cm', 'Weight': '441.0 kg'}

In [398]:
# use .str.replace to replace all single quotes
df['Measurements'] = df['Measurements'].str.replace("'",'"')

## Apple json.loads to full column
df['Measurements'] = df['Measurements'].apply(json.loads)
df['Measurements'].head()

0    {'Height': '203.0 cm', 'Weight': '441.0 kg'}
1     {'Height': '191.0 cm', 'Weight': '65.0 kg'}
2     {'Height': '185.0 cm', 'Weight': '90.0 kg'}
3    {'Height': '203.0 cm', 'Weight': '441.0 kg'}
4    {'Height': '193.0 cm', 'Weight': '122.0 kg'}
Name: Measurements, dtype: object

In [399]:
## check a single value after transformation
test_coord = df.loc[0, 'Measurements']
print(type(test_coord))
test_coord

<class 'dict'>

{'Height': '203.0 cm', 'Weight': '441.0 kg'}

**Splitting Dictionary**

In [400]:
height_weight = df['Measurements'].apply(pd.Series)
height_weight

       Height    Weight
0    203.0 cm  441.0 kg
1    191.0 cm   65.0 kg
2    185.0 cm   90.0 kg
3    203.0 cm  441.0 kg
4    193.0 cm  122.0 kg
..        ...       ...
458  183.0 cm   83.0 kg
459  165.0 cm   52.0 kg
460   66.0 cm   17.0 kg
461  170.0 cm   57.0 kg
462  185.0 cm   81.0 kg

[463 rows x 2 columns]

In [401]:
# Add to dataframe and drop original column

df = pd.concat((df, height_weight), axis = 1)

df = df.drop(columns=['Measurements'])
df.info()
df.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 463 entries, 0 to 462
Data columns (total 10 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Gender      463 non-null    object
 1   Race        463 non-null    object
 2   Alignment   463 non-null    object
 3   Hair color  463 non-null    object
 4   Eye color   463 non-null    object
 5   Skin color  463 non-null    object
 6   Hero        463 non-null    object
 7   Publisher   463 non-null    object
 8   Height      463 non-null    object
 9   Weight      463 non-null    object
dtypes: object(10)
memory usage: 36.3+ KB

,Gender,Race,Alignment,Hair color,Eye color,Skin color,Hero,Publisher,Height,Weight
0,Male,Human,good,No Hair,yellow,Unknown,A-Bomb,Marvel Comics,203.0 cm,441.0 kg
1,Male,Icthyo Sapien,good,No Hair,blue,blue,Abe Sapien,Dark Horse Comics,191.0 cm,65.0 kg
2,Male,Ungaran,good,No Hair,blue,red,Abin Sur,DC Comics,185.0 cm,90.0 kg
3,Male,Human / Radiation,bad,No Hair,green,Unknown,Abomination,Marvel Comics,203.0 cm,441.0 kg
4,Male,Human,bad,No Hair,blue,Unknown,Absorbing Man,Marvel Comics,193.0 cm,122.0 kg

**Fixing Height Column**

In [402]:
## adding expand=True
df['Height'].str.split(' ',expand=True)

         0   1
0    203.0  cm
1    191.0  cm
2    185.0  cm
3    203.0  cm
4    193.0  cm
..     ...  ..
458  183.0  cm
459  165.0  cm
460   66.0  cm
461  170.0  cm
462  185.0  cm

[463 rows x 2 columns]

In [403]:
df[['Height_cm', 'Units']] = df['Height'].str.split(' ',expand=True)
df.head()

,Gender,Race,Alignment,Hair color,Eye color,Skin color,Hero,Publisher,Height,Weight,Height_cm,Units
0,Male,Human,good,No Hair,yellow,Unknown,A-Bomb,Marvel Comics,203.0 cm,441.0 kg,203.0,cm
1,Male,Icthyo Sapien,good,No Hair,blue,blue,Abe Sapien,Dark Horse Comics,191.0 cm,65.0 kg,191.0,cm
2,Male,Ungaran,good,No Hair,blue,red,Abin Sur,DC Comics,185.0 cm,90.0 kg,185.0,cm
3,Male,Human / Radiation,bad,No Hair,green,Unknown,Abomination,Marvel Comics,203.0 cm,441.0 kg,203.0,cm
4,Male,Human,bad,No Hair,blue,Unknown,Absorbing Man,Marvel Comics,193.0 cm,122.0 kg,193.0,cm

In [404]:
df = df.drop(columns = ['Units', 'Height'])
df.head()

,Gender,Race,Alignment,Hair color,Eye color,Skin color,Hero,Publisher,Weight,Height_cm
0,Male,Human,good,No Hair,yellow,Unknown,A-Bomb,Marvel Comics,441.0 kg,203.0
1,Male,Icthyo Sapien,good,No Hair,blue,blue,Abe Sapien,Dark Horse Comics,65.0 kg,191.0
2,Male,Ungaran,good,No Hair,blue,red,Abin Sur,DC Comics,90.0 kg,185.0
3,Male,Human / Radiation,bad,No Hair,green,Unknown,Abomination,Marvel Comics,441.0 kg,203.0
4,Male,Human,bad,No Hair,blue,Unknown,Absorbing Man,Marvel Comics,122.0 kg,193.0

**Fixing Weight Column**

In [405]:
## adding expand=True
df['Weight'].str.split(' ',expand=True)

         0   1
0    441.0  kg
1     65.0  kg
2     90.0  kg
3    441.0  kg
4    122.0  kg
..     ...  ..
458   83.0  kg
459   52.0  kg
460   17.0  kg
461   57.0  kg
462   81.0  kg

[463 rows x 2 columns]

In [406]:
df[['Weight_kg', 'Units2']] = df['Weight'].str.split(' ',expand=True)
df.head()

,Gender,Race,Alignment,Hair color,Eye color,Skin color,Hero,Publisher,Weight,Height_cm,Weight_kg,Units2
0,Male,Human,good,No Hair,yellow,Unknown,A-Bomb,Marvel Comics,441.0 kg,203.0,441.0,kg
1,Male,Icthyo Sapien,good,No Hair,blue,blue,Abe Sapien,Dark Horse Comics,65.0 kg,191.0,65.0,kg
2,Male,Ungaran,good,No Hair,blue,red,Abin Sur,DC Comics,90.0 kg,185.0,90.0,kg
3,Male,Human / Radiation,bad,No Hair,green,Unknown,Abomination,Marvel Comics,441.0 kg,203.0,441.0,kg
4,Male,Human,bad,No Hair,blue,Unknown,Absorbing Man,Marvel Comics,122.0 kg,193.0,122.0,kg

In [407]:
df = df.drop(columns = ['Units2', 'Weight'])
df.head(2)

,Gender,Race,Alignment,Hair color,Eye color,Skin color,Hero,Publisher,Height_cm,Weight_kg
0,Male,Human,good,No Hair,yellow,Unknown,A-Bomb,Marvel Comics,203.0,441.0
1,Male,Icthyo Sapien,good,No Hair,blue,blue,Abe Sapien,Dark Horse Comics,191.0,65.0

In [408]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 463 entries, 0 to 462
Data columns (total 10 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Gender      463 non-null    object
 1   Race        463 non-null    object
 2   Alignment   463 non-null    object
 3   Hair color  463 non-null    object
 4   Eye color   463 non-null    object
 5   Skin color  463 non-null    object
 6   Hero        463 non-null    object
 7   Publisher   463 non-null    object
 8   Height_cm   463 non-null    object
 9   Weight_kg   463 non-null    object
dtypes: object(10)
memory usage: 36.3+ KB

**Converting Height and Weight to Float**

In [409]:
df['Height_cm'] = df['Height_cm'].astype(float)
print(df.dtypes)

Gender         object
Race           object
Alignment      object
Hair color     object
Eye color      object
Skin color     object
Hero           object
Publisher      object
Height_cm     float64
Weight_kg      object
dtype: object

In [410]:
df['Weight_kg'] = df['Weight_kg'].astype(float)
print(df.dtypes)

Gender         object
Race           object
Alignment      object
Hair color     object
Eye color      object
Skin color     object
Hero           object
Publisher      object
Height_cm     float64
Weight_kg     float64
dtype: object

In [411]:
df.to_csv('advanced2_tf_data_pt1.csv', index = False)

## Powers Dataframe

In [412]:
df2.info()
df2.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 667 entries, 0 to 666
Data columns (total 2 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   hero_names  667 non-null    object
 1   Powers      667 non-null    object
dtypes: object(2)
memory usage: 10.5+ KB

    hero_names                                             Powers
0      3-D Man         Agility,Super Strength,Stamina,Super Speed
1       A-Bomb  Accelerated Healing,Durability,Longevity,Super...
2   Abe Sapien  Agility,Accelerated Healing,Cold Resistance,Du...
3     Abin Sur                                 Lantern Power Ring
4  Abomination  Accelerated Healing,Intelligence,Super Strengt...

In [413]:
df2['Powers'].value_counts()

Intelligence                                                                                                                                                                                                                                                         8
Durability,Super Strength                                                                                                                                                                                                                                            5
Agility,Stealth,Marksmanship,Weapons Master,Stamina                                                                                                                                                                                                                  4
Marksmanship                                                                                                                                                                                                                                                         4
Teleportation                                                                                                                                                                                                                                                        4
                                                                                                                                                                                                                                                                    ..
Accelerated Healing,Flight,Telepathy,Energy Blasts,Teleportation,Telekinesis,Astral Projection,Psionic Powers,Mind Blast,Regeneration,Illusions,Resurrection                                                                                                         1
Flight,Telepathy,Animal Oriented Powers,Gliding                                                                                                                                                                                                                      1
Accelerated Healing,Durability,Energy Absorption,Flight,Super Strength,Telepathy,Energy Blasts,Size Changing,Super Speed,Darkforce Manipulation,Enhanced Senses,Phasing,Invulnerability,Self-Sustenance,Gravity Control,Energy Manipulation,Time Travel,Illusions    1
Agility,Accelerated Healing,Super Strength,Super Speed,Animal Oriented Powers,Enhanced Senses,Jump,Reflexes,Natural Weapons                                                                                                                                          1
Super Speed,Intangibility,Time Travel,Time Manipulation                                                                                                                                                                                                              1
Name: Powers, Length: 608, dtype: int64

In [414]:
## adding expand=True
df2['powers_split'] = df2['Powers'].str.split(',',expand=False)

In [415]:
df2.head(2)

,hero_names,Powers,powers_split
0,3-D Man,"Agility,Super Strength,Stamina,Super Speed","[Agility, Super Strength, Stamina, Super Speed]"
1,A-Bomb,"Accelerated Healing,Durability,Longevity,Super...","[Accelerated Healing, Durability, Longevity, S..."

In [416]:
## exploding the column of lists

exploded = df2.explode('powers_split')
exploded[['hero_names','Powers', 'powers_split']].head(5)

,hero_names,Powers,powers_split
0,3-D Man,"Agility,Super Strength,Stamina,Super Speed",Agility
0,3-D Man,"Agility,Super Strength,Stamina,Super Speed",Super Strength
0,3-D Man,"Agility,Super Strength,Stamina,Super Speed",Stamina
0,3-D Man,"Agility,Super Strength,Stamina,Super Speed",Super Speed
1,A-Bomb,"Accelerated Healing,Durability,Longevity,Super...",Accelerated Healing

In [417]:
## saving the unique values from the exploded column
cols_to_make = exploded['powers_split'].dropna().unique()
cols_to_make

array(['Agility', 'Super Strength', 'Stamina', 'Super Speed',
       'Accelerated Healing', 'Durability', 'Longevity', 'Camouflage',
       'Self-Sustenance', 'Cold Resistance', 'Underwater breathing',
       'Marksmanship', 'Weapons Master', 'Intelligence', 'Telepathy',
       'Immortality', 'Reflexes', 'Enhanced Sight', 'Sub-Mariner',
       'Lantern Power Ring', 'Invulnerability', 'Animation',
       'Super Breath', 'Dimensional Awareness', 'Flight', 'Size Changing',
       'Teleportation', 'Magic', 'Dimensional Travel',
       'Molecular Manipulation', 'Energy Manipulation', 'Power Cosmic',
       'Energy Absorption', 'Elemental Transmogrification',
       'Fire Resistance', 'Natural Armor', 'Heat Resistance',
       'Matter Absorption', 'Regeneration', 'Stealth', 'Power Suit',
       'Energy Blasts', 'Energy Beams', 'Heat Generation', 'Danger Sense',
       'Phasing', 'Force Fields', 'Hypnokinesis', 'Invisibility',
       'Enhanced Senses', 'Jump', 'Shapeshifting', 'Elasticity',
       'Substance Secretion', 'Enhanced Hearing', 'Adaptation', 'Gliding',
       'Natural Weapons', 'Wallcrawling', 'Vision - Thermal',
       'Power Augmentation', 'Cryokinesis', 'Duplication',
       'Weapon-based Powers', 'Fire Control', 'Enhanced Memory',
       'Energy Constructs', 'Power Absorption', 'Time Travel',
       'Enhanced Smell', 'Water Control', 'Vision - Telescopic',
       'Magnetism', 'Vision - Microscopic', 'Vision - Night',
       'Vision - Heat', 'Vision - X-Ray', 'Psionic Powers',
       'Toxin and Disease Resistance', 'Animal Attributes',
       'Animal Oriented Powers', 'Toxin and Disease Control', 'Empathy',
       'Animal Control', 'Darkforce Manipulation', 'Time Manipulation',
       'Reality Warping', 'Web Creation', 'Symbiote Costume',
       'Telekinesis', 'Levitation', 'Biokinesis', 'Sonar',
       'Enhanced Touch', 'Seismic Power', 'Energy Armor',
       'Omnilingualism', 'Radiation Immunity', 'Density Control',
       'Light Control', 'Illumination', 'Molecular Combustion',
       'Astral Travel', 'Precognition', 'Intangibility', 'Illusions',
       'Audio Control', 'Sonic Scream', 'Peak Human Condition',
       'Vision - Infrared', 'Dexterity', 'Omnitrix', 'Omnipotent',
       'Possession', 'Energy Resistance', 'Vision - Cryo', 'Mind Control',
       'Mind Blast', 'Clairvoyance', 'Probability Manipulation',
       'Death Touch', 'Electrokinesis', 'Gravity Control',
       'Technopath/Cyberpath', 'Radar Sense', 'Astral Projection',
       'Cloaking', 'Telepathy Resistance', 'Mind Control Resistance',
       'Hyperkinesis', 'Spatial Awareness', 'Radiation Control',
       'Radiation Absorption', 'Magic Resistance', 'Element Control',
       'Plant Control', 'Terrakinesis', 'Power Sense', 'Wind Control',
       'Qwardian Power Ring', 'Echolocation', 'Resurrection', 'The Force',
       'Summoning', 'Banish', 'Molecular Dissipation',
       'Electrical Transport', 'Speed Force', 'Grim Reaping',
       'Portal Creation', 'Vitakinesis', 'Projection', 'Insanity',
       'Photographic Reflexes', 'Anti-Gravity', 'Thirstokinesis',
       'Power Nullifier', 'Weather Control', 'Omnipresent', 'Omniscient',
       'Hair Manipulation', 'Nova Force', 'Odin Force', 'Phoenix Force',
       'Intuitive aptitude', 'Melting', 'Changing Armor'], dtype=object)

In [418]:
for col in cols_to_make:
    df2[col] = df2['Powers'].str.contains(col)
df2.head()

/var/folders/fp/jpcv35096h9d0ylkqvbwx2xm0000gn/T/ipykernel_16796/4218022820.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df2[col] = df2['Powers'].str.contains(col)
/var/folders/fp/jpcv35096h9d0ylkqvbwx2xm0000gn/T/ipykernel_16796/4218022820.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df2[col] = df2['Powers'].str.contains(col)
/var/folders/fp/jpcv35096h9d0ylkqvbwx2xm0000gn/T/ipykernel_16796/4218022820.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df2[col] = df2['Powers'].str.contains(col)
/var/folders/fp/jpcv35096h9d0ylkqvbwx2xm0000gn/T/ipykernel_16796/4218022820.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df2[col] = df2['Powers'].str.contains(col)
/var/folders/fp/jpcv35096h9d0ylkqvbwx2xm0000gn/T/ipykernel_16796/4218022820.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df2[col] = df2['Powers'].str.contains(col)
/var/folders/fp/jpcv35096h9d0ylkqvbwx2xm0000gn/T/ipykernel_16796/4218022820.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df2[col] = df2['Powers'].str.contains(col)
/var/folders/fp/jpcv35096h9d0ylkqvbwx2xm0000gn/T/ipykernel_16796/4218022820.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df2[col] = df2['Powers'].str.contains(col)
/var/folders/fp/jpcv35096h9d0ylkqvbwx2xm0000gn/T/ipykernel_16796/4218022820.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df2[col] = df2['Powers'].str.contains(col)
/var/folders/fp/jpcv35096h9d0ylkqvbwx2xm0000gn/T/ipykernel_16796/4218022820.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df2[col] = df2['Powers'].str.contains(col)
/var/folders/fp/jpcv35096h9d0ylkqvbwx2xm0000gn/T/ipykernel_16796/4218022820.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df2[col] = df2['Powers'].str.contains(col)
/var/folders/fp/jpcv35096h9d0ylkqvbwx2xm0000gn/T/ipykernel_16796/4218022820.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df2[col] = df2['Powers'].str.contains(col)
/var/folders/fp/jpcv35096h9d0ylkqvbwx2xm0000gn/T/ipykernel_16796/4218022820.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df2[col] = df2['Powers'].str.contains(col)
/var/folders/fp/jpcv35096h9d0ylkqvbwx2xm0000gn/T/ipykernel_16796/4218022820.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df2[col] = df2['Powers'].str.contains(col)
/var/folders/fp/jpcv35096h9d0ylkqvbwx2xm0000gn/T/ipykernel_16796/4218022820.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df2[col] = df2['Powers'].str.contains(col)
/var/folders/fp/jpcv35096h9d0ylkqvbwx2xm0000gn/T/ipykernel_16796/4218022820.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df2[col] = df2['Powers'].str.contains(col)
/var/folders/fp/jpcv35096h9d0ylkqvbwx2xm0000gn/T/ipykernel_16796/4218022820.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df2[col] = df2['Powers'].str.contains(col)
/var/folders/fp/jpcv35096h9d0ylkqvbwx2xm0000gn/T/ipykernel_16796/4218022820.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df2[col] = df2['Powers'].str.contains(col)
/var/folders/fp/jpcv35096h9d0ylkqvbwx2xm0000gn/T/ipykernel_16796/4218022820.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df2[col] = df2['Powers'].str.contains(col)
/var/folders/fp/jpcv35096h9d0ylkqvbwx2xm0000gn/T/ipykernel_16796/4218022820.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df2[col] = df2['Powers'].str.contains(col)
/var/folders/fp/jpcv35096h9d0ylkqvbwx2xm0000gn/T/ipykernel_16796/4218022820.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df2[col] = df2['Powers'].str.contains(col)
/var/folders/fp/jpcv35096h9d0ylkqvbwx2xm0000gn/T/ipykernel_16796/4218022820.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df2[col] = df2['Powers'].str.contains(col)
/var/folders/fp/jpcv35096h9d0ylkqvbwx2xm0000gn/T/ipykernel_16796/4218022820.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df2[col] = df2['Powers'].str.contains(col)
/var/folders/fp/jpcv35096h9d0ylkqvbwx2xm0000gn/T/ipykernel_16796/4218022820.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df2[col] = df2['Powers'].str.contains(col)
/var/folders/fp/jpcv35096h9d0ylkqvbwx2xm0000gn/T/ipykernel_16796/4218022820.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df2[col] = df2['Powers'].str.contains(col)
/var/folders/fp/jpcv35096h9d0ylkqvbwx2xm0000gn/T/ipykernel_16796/4218022820.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df2[col] = df2['Powers'].str.contains(col)
/var/folders/fp/jpcv35096h9d0ylkqvbwx2xm0000gn/T/ipykernel_16796/4218022820.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df2[col] = df2['Powers'].str.contains(col)
/var/folders/fp/jpcv35096h9d0ylkqvbwx2xm0000gn/T/ipykernel_16796/4218022820.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df2[col] = df2['Powers'].str.contains(col)
/var/folders/fp/jpcv35096h9d0ylkqvbwx2xm0000gn/T/ipykernel_16796/4218022820.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df2[col] = df2['Powers'].str.contains(col)
/var/folders/fp/jpcv35096h9d0ylkqvbwx2xm0000gn/T/ipykernel_16796/4218022820.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df2[col] = df2['Powers'].str.contains(col)
/var/folders/fp/jpcv35096h9d0ylkqvbwx2xm0000gn/T/ipykernel_16796/4218022820.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df2[col] = df2['Powers'].str.contains(col)
/var/folders/fp/jpcv35096h9d0ylkqvbwx2xm0000gn/T/ipykernel_16796/4218022820.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df2[col] = df2['Powers'].str.contains(col)
/var/folders/fp/jpcv35096h9d0ylkqvbwx2xm0000gn/T/ipykernel_16796/4218022820.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df2[col] = df2['Powers'].str.contains(col)
/var/folders/fp/jpcv35096h9d0ylkqvbwx2xm0000gn/T/ipykernel_16796/4218022820.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df2[col] = df2['Powers'].str.contains(col)
/var/folders/fp/jpcv35096h9d0ylkqvbwx2xm0000gn/T/ipykernel_16796/4218022820.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df2[col] = df2['Powers'].str.contains(col)
/var/folders/fp/jpcv35096h9d0ylkqvbwx2xm0000gn/T/ipykernel_16796/4218022820.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df2[col] = df2['Powers'].str.contains(col)
/var/folders/fp/jpcv35096h9d0ylkqvbwx2xm0000gn/T/ipykernel_16796/4218022820.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df2[col] = df2['Powers'].str.contains(col)
/var/folders/fp/jpcv35096h9d0ylkqvbwx2xm0000gn/T/ipykernel_16796/4218022820.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df2[col] = df2['Powers'].str.contains(col)
/var/folders/fp/jpcv35096h9d0ylkqvbwx2xm0000gn/T/ipykernel_16796/4218022820.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df2[col] = df2['Powers'].str.contains(col)
/var/folders/fp/jpcv35096h9d0ylkqvbwx2xm0000gn/T/ipykernel_16796/4218022820.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df2[col] = df2['Powers'].str.contains(col)
/var/folders/fp/jpcv35096h9d0ylkqvbwx2xm0000gn/T/ipykernel_16796/4218022820.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df2[col] = df2['Powers'].str.contains(col)
/var/folders/fp/jpcv35096h9d0ylkqvbwx2xm0000gn/T/ipykernel_16796/4218022820.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df2[col] = df2['Powers'].str.contains(col)
/var/folders/fp/jpcv35096h9d0ylkqvbwx2xm0000gn/T/ipykernel_16796/4218022820.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df2[col] = df2['Powers'].str.contains(col)
/var/folders/fp/jpcv35096h9d0ylkqvbwx2xm0000gn/T/ipykernel_16796/4218022820.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df2[col] = df2['Powers'].str.contains(col)
/var/folders/fp/jpcv35096h9d0ylkqvbwx2xm0000gn/T/ipykernel_16796/4218022820.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df2[col] = df2['Powers'].str.contains(col)
/var/folders/fp/jpcv35096h9d0ylkqvbwx2xm0000gn/T/ipykernel_16796/4218022820.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df2[col] = df2['Powers'].str.contains(col)
/var/folders/fp/jpcv35096h9d0ylkqvbwx2xm0000gn/T/ipykernel_16796/4218022820.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df2[col] = df2['Powers'].str.contains(col)
/var/folders/fp/jpcv35096h9d0ylkqvbwx2xm0000gn/T/ipykernel_16796/4218022820.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df2[col] = df2['Powers'].str.contains(col)
/var/folders/fp/jpcv35096h9d0ylkqvbwx2xm0000gn/T/ipykernel_16796/4218022820.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df2[col] = df2['Powers'].str.contains(col)
/var/folders/fp/jpcv35096h9d0ylkqvbwx2xm0000gn/T/ipykernel_16796/4218022820.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df2[col] = df2['Powers'].str.contains(col)

,hero_names,Powers,powers_split,Agility,Super Strength,Stamina,Super Speed,Accelerated Healing,Durability,Longevity,...,Weather Control,Omnipresent,Omniscient,Hair Manipulation,Nova Force,Odin Force,Phoenix Force,Intuitive aptitude,Melting,Changing Armor
0,3-D Man,"Agility,Super Strength,Stamina,Super Speed","[Agility, Super Strength, Stamina, Super Speed]",True,True,True,True,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,A-Bomb,"Accelerated Healing,Durability,Longevity,Super...","[Accelerated Healing, Durability, Longevity, S...",False,True,True,False,True,True,True,...,False,False,False,False,False,False,False,False,False,False
2,Abe Sapien,"Agility,Accelerated Healing,Cold Resistance,Du...","[Agility, Accelerated Healing, Cold Resistance...",True,True,True,False,True,True,True,...,False,False,False,False,False,False,False,False,False,False
3,Abin Sur,Lantern Power Ring,[Lantern Power Ring],False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,Abomination,"Accelerated Healing,Intelligence,Super Strengt...","[Accelerated Healing, Intelligence, Super Stre...",False,True,True,True,True,False,False,...,False,False,False,False,False,False,False,False,False,False

In [419]:
# Drop Powers Column

df2 = df2.drop(columns=['Powers', 'powers_split'])
df2.to_csv('advanced_tf_data_pt1.csv', index = False)

## Merging

In [423]:
# Hero Info DF
left_df = pd.read_csv('advanced2_tf_data_pt1.csv')
# Powers DF
right_df = pd.read_csv('advanced_tf_data_pt1.csv')

In [424]:
## merging with different column names
merged = pd.merge(left_df, right_df, left_on='Hero', right_on='hero_names')
merged.head()

,Gender,Race,Alignment,Hair color,Eye color,Skin color,Hero,Publisher,Height_cm,Weight_kg,...,Weather Control,Omnipresent,Omniscient,Hair Manipulation,Nova Force,Odin Force,Phoenix Force,Intuitive aptitude,Melting,Changing Armor
0,Male,Human,good,No Hair,yellow,Unknown,A-Bomb,Marvel Comics,203.0,441.0,...,False,False,False,False,False,False,False,False,False,False
1,Male,Icthyo Sapien,good,No Hair,blue,blue,Abe Sapien,Dark Horse Comics,191.0,65.0,...,False,False,False,False,False,False,False,False,False,False
2,Male,Ungaran,good,No Hair,blue,red,Abin Sur,DC Comics,185.0,90.0,...,False,False,False,False,False,False,False,False,False,False
3,Male,Human / Radiation,bad,No Hair,green,Unknown,Abomination,Marvel Comics,203.0,441.0,...,False,False,False,False,False,False,False,False,False,False
4,Male,Human,bad,No Hair,blue,Unknown,Absorbing Man,Marvel Comics,193.0,122.0,...,False,False,False,False,False,False,False,False,False,False